ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_is_custom BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE identities ADD COLUMN IF NOT EXISTS avatar TEXT;
ALTER TABLE identities ADD COLUMN IF NOT EXISTS username TEXT;
